name: my-first-workflow

on: 
    push

jobs: 
    first_job:
        runs-on: self-hosted
        steps:
        - name: checkout
          uses: actions/checkout@v4    
        - name: welcome message
          run: echo "hello welcome to my first job"
        - name: list files
          run: ls 
        - name: multiline commands
          run: |
            echo "hello"
            ls -lrta
            cat README.md       